apiVersion: v2
name: helm
description: Documentation generator for helm Ansible role
home: https://helm.baltorepo.com/stable/debian/packages/helm/releases
version: 3.18.3-1
dependencies:
  - name: diff
    repository: https://github.com/databus23/helm-diff
    version: 3.12.2
