apiVersion: v2
name: victoria-logs-single
description: Documentation generator for victoria-logs Ansible role
home: https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.9.2
appVersion: 1.0.0
