apiVersion: v2
name: cilium
description: Documentation generator for cilium Ansible role
home: https://github.com/cilium/cilium
dependencies:
  - name: cilium-cli
    repository: https://github.com/cilium/cilium-cli
    version: 0.16.22
  - name: gateway-api
    repository: https://github.com/kubernetes-sigs/gateway-api
    version: 1.2.1
  - name: hubble
    repository: https://github.com/cilium/hubble
    version: 1.16.5
type: application
version: 1.16.5
appVersion: 1.0.0
