apiVersion: v2
name: cilium
description: Documentation generator for cilium Ansible role
home: https://github.com/cilium/cilium
version: 1.18.2
dependencies:
  - name: cilium-cli
    repository: https://github.com/cilium/cilium-cli
    version: 0.18.6
  - name: gateway-api
    repository: https://github.com/kubernetes-sigs/gateway-api
    version: 1.4.1
  - name: hubble
    repository: https://github.com/cilium/hubble
    version: 1.18.0
