---
- name: Reboot
  ansible.builtin.reboot:
  register: reboot

- name: Restart loadbalancer services
  ansible.builtin.systemd_service:
    name: '{{ item }}.service'
    state: restarted
    daemon_reload: true
    enabled: true
  loop:
    - haproxy
    - keepalived

- name: Reload mail service
  ansible.builtin.systemd_service:
    name: postfix.service
    state: reloaded
    enabled: true
  when: not reboot.changed

- name: Restart unattended upgrades service
  ansible.builtin.systemd_service:
    name: unattended-upgrades.service
    state: restarted
    enabled: true
  when: not reboot.changed
