apiVersion: v2
name: argo-cd
description: Documentation generator for argo-cd Ansible role
home: https://github.com/argoproj/argo-helm
dependencies:
  - name: argocd
    repository: https://github.com/argoproj/argo-cd
    version: 2.13.4
type: application
version: 7.8.0
appVersion: 1.0.0
