apiVersion: v2
name: argo-cd
description: Documentation generator for argo-cd Ansible role
home: https://github.com/argoproj/argo-helm
dependencies:
  - name: argocd
    repository: https://github.com/argoproj/argo-cd
    version: 2.14.1
type: application
version: 7.7.22
appVersion: 1.0.0
