apiVersion: v2
name: longhorn
description: Documentation generator for longhorn Ansible role
home: https://github.com/longhorn/charts
type: application
version: 1.8.1
appVersion: 1.0.0
dependencies:
  - name: longhornctl
    repository: https://github.com/longhorn/cli
    version: 1.8.1
