---
victoriametrics_vars:
  kubernetes:
    alertmanager:
      config:
        route:
          group_interval: 5m
          group_wait: 30s
          repeat_interval: 12h
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
        subdomain: alertmanager
      log_level: WARN
      # -- Minimum accepted value is `2`
      replicas: 2
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      storage:
        enabled: false
        access_modes:
          - ReadWriteOnce
        class: longhorn
        size: 5Gi
    default_dashboards:
      timezone: utc
    helm:
      chart:
        alias: vmks
        name: victoria-metrics-k8s-stack
        version: v0.38.0
      repository:
        grafana:
          name: helm-charts
          org: grafana
          url: https://grafana.github.io
        prometheus:
          name: helm-charts
          org: prometheus-community
          url: https://prometheus-community.github.io
        victoriametrics:
          name: helm-charts
          org: VictoriaMetrics
          url: https://victoriametrics.github.io
    grafana:
      ingress:
        enabled: true
        # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
        subdomain: grafana
      log_level: WARN
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      sidecar:
        log_level: WARN
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      user:
        # -- (string) User name used to access Grafana UI
        # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) `credentials` collection
        name:
        # -- (string) User password used to access Grafana UI
        # @default -- Set value into [all.yaml](../../inventory/cluster/group_vars/all.yaml) `credentials` collection
        password:
    kube_state_metrics:
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    namespace: kube-system
    victoria_metrics_operator:
      # -- Available options are `info` and `error`
      log_level: error
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    prometheus_node_exporter:
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    vmagent:
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
        subdomain: agent
      log_level: WARN
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 1024Mi
        requests:
          cpu: 10m
          memory: 1024Mi
      storage:
        enabled: false
        access_modes:
          - ReadWriteOnce
        class: longhorn
        size: 5Gi
    vmalert:
      config_reloader:
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      ingress:
        enabled: true
        # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
        subdomain: alert
      log_level: WARN
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
    vmcluster:
      # -- If false, `vmsingle` settings are used
      enabled: false
      replication_factor: 2
      retention_period: 72h
      vminsert:
        hpa:
          enabled: true
          min_replicas: 2
          max_replicas: 4
          resource:
            name: memory
            target:
              utilization: 80
        ingress:
          enabled: false
          # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
          subdomain: insert
        log_level: WARN
        resources:
          limits:
            cpu: null
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
      vmselect:
        hpa:
          enabled: true
          min_replicas: 2
          max_replicas: 4
          resource:
            name: memory
            target:
              utilization: 80
        ingress:
          enabled: true
          # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
          subdomain: metrics
        log_level: WARN
        resources:
          limits:
            cpu: null
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
        storage:
          enabled: false
          access_modes:
            - ReadWriteOnce
          class: longhorn
          size: 5Gi
      vmstorage:
        ingress:
          enabled: false
          # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
          subdomain: storage
        log_level: WARN
        replicas: 1
        resources:
          limits:
            cpu: null
            memory: 2560Mi
          requests:
            cpu: 10m
            memory: 2560Mi
        storage:
          enabled: true
          access_modes:
            - ReadWriteOnce
          class: longhorn
          size: 50Gi
    vmsingle:
      ingress:
        enabled: true
        # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#front-ends), for details
        subdomain: metrics
      log_level: WARN
      replicas: 1
      resources:
        limits:
          cpu: null
          memory: 2560Mi
        requests:
          cpu: 10m
          memory: 2560Mi
      retention_period: 72h
      storage:
        enabled: true
        access_modes:
          - ReadWriteOnce
        class: longhorn
        size: 50Gi
