---
ansible_user: hunter2
# -- Encrypt value with [`ansible-vault`](https://axivo.com/k3s-cluster/tutorials/handbook/ansible/#vault)
ansible_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65353636613630653631376461623336623839623565313662313463643836353666363036636331
  3832326563366638633036643164303064393738343464330a383861643032336231653665653233
  36306430373037643433373735373834333565626634633037616437363537336137626530666537
  6262343137663235620a353362356464386463363131343539646638646333373732373933373033
  6231
ansible_become_password: '{{ ansible_password }}'
global_map:
  ansible:
    version: 2.19.0
  credentials:
    argocd:
      server:
        admin:
          # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/argocd/#credentials), for details
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            61333835306265343864656666356562306365333232653536303666383363653863653839303064
            3566313830613432656361633132653539316532336235390a346565626562366163343965656436
            63323266313663633639306239623634643838333263306663326430643138373039333431666161
            3632373864363837640a363138386632616264653636656637656637363435623032356531616263
            62366165626330326561303231316539656238666366386339616665633961326437
        user:
          name: tj
          # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/argocd/#credentials), for details
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            66356563666664363963616564396338626265633635383639663061383135396661353636633165
            3437633338646264633065306539373131633137373465360a623561306539613638336434343864
            65306364663034613063306439336266383764393537393631663664643132633363313131633831
            3839363863643366310a333734613265393365353563613962386231646535653933663864366366
            35346632353161646235363739366365303732326636383663396232353563313563
    cluster:
      postfix:
        user:
          # -- Use `alias@icloud.com` format, see [details](https://support.apple.com/guide/icloud/mm6b1a490a)
          alias: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            31306138626536353939666366663436356361656238383465643764646539663636323364613335
            3139613563666230336231666330353130663833373261620a663230653035666663363133386661
            66366665373337373938623864633764346632333733643833353939363865386233623434313034
            6634363335303630340a636430356639616338356661633166653330373930623731353638626466
            39353665613633643039363566336130333337313362373663326231616538316662
          # -- Use `username@icloud.com` format, see [details](https://support.apple.com/guide/icloud/mmdd8d1c5c)
          name: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            31306138626536353939666366663436356361656238383465643764646539663636323364613335
            3139613563666230336231666330353130663833373261620a663230653035666663363133386661
            66366665373337373938623864633764346632333733643833353939363865386233623434313034
            6634363335303630340a636430356639616338356661633166653330373930623731353638626466
            39353665613633643039363566336130333337313362373663326231616538316662
          # -- App-specific [password](https://support.apple.com/HT204397), used for iCloud mail server authentication
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            64653936383736396533666230363731363361333262336138363839636331323466623937633362
            3338633964653466383834376566333431346266636264660a313362353933663163346336323536
            33333034363764653838653836653165626137386163353566646665626361613131653233396466
            3263336530396438360a306239643933376165656465383964343036396532636465386431336561
            32333466656633623462643931303936313730353537393639346635396262393533653936376162
            38383734646532346463303836333730633831633065343535306564613762343035343137326431
            366334623732323664653064633763626662
    externaldns:
      cloudflare:
        api:
          # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/externaldns/#cloudflare), for details
          token: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            64316533653632343835663066376565646137663164616234346362323237663463363237623166
            3238383938643539326438616239303362333466316236300a383134313363643235636166346433
            34316232353333386661633737663730383265303436356631623761323633386239623136396334
            3530653433333234630a303765623861353361613334623839623966656132366137323632633362
            35333863646639343334666239383539363363613232636462383839326138383061646661393538
            3436663563646662346435383738616130653231363865643234
    kured:
      slack:
        notify:
          # -- See [documentation](https://axivo.com/k3s-cluster/tutorials/handbook/kured/#slack), for details
          url: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            37363838373830323834376534623362346635633134353962316636353662393465666239623436
            6631633264633831663363636239656464343630363266380a633664643361303638376462376433
            35393662386634666437356166383963393934366438633630656439656663363131663536306434
            3434343962306132610a396635366435363164633662333864613334376266356532393635396662
            62343932613632313366643634626531333461663061616235656131316236613939383666353465
            38373036663864646439363561653666383166643138346163393739653566396238333235393934
            66616166386435616233323561623537343762333061323033663861383764633039346639373430
            30643237666166653565626435653632633533613937366663653933643866646566316566353734
            64663137366233653132323463666233363731383931383061366233616666316430
    longhorn:
      backup:
        user:
          name: hunter2
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            31333265626164626639303366303633636334303938376138333065376138336334643065383633
            3261346565323230373839643137353666346366613136310a613537663664363334366666363366
            33343534373963336431303834383364323533396237393232353034303966613565343636343565
            3230313735313132340a616239636630313838373936326166393665626339326135373530633762
            37306436373130346432386136353538376632636166623938646164383533313735
    victoriametrics:
      grafana:
        user:
          name: admin
          password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            65633835363338643765396439663432366433653864343066323334353938383666343864616337
            3566633138353266633961623832316535306335333232380a393665336363623739666435306131
            34346461663465323531623466316163373461383063623062303333306565356466613762323630
            6238353636353037650a353636393633306638626435336239653438323138343363393564333532
            34323265333666636237666636373764316233343734636638346663623766323263
  tags:
    play:
      - charts
      - cluster
      - kubernetes
    role:
      - argo-cd
      - cert-manager
      - cilium
      - cluster
      - coredns
      - external-dns
      - helm
      - k3s
      - kured
      - longhorn
      - metrics-server
      - victoria-logs
      - victoria-metrics
