apiVersion: v2
name: cert-manager
description: Documentation generator for cert-manager Ansible role
home: https://github.com/cert-manager/cert-manager
version: 1.18.0
dependencies:
  - name: cmctl
    repository: https://github.com/cert-manager/cmctl
    version: 2.1.1
