---
- name: Set authorized key
  ansible.posix.authorized_key:
    key: "{{ lookup('ansible.builtin.file', cluster_map.ssh.authorized_key) }}"
    user: '{{ ansible_user }}'

- name: Create sudoers file
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL\n"
    dest: '/etc/sudoers.d/{{ ansible_user }}'
    owner: root
    group: root
    mode: '0440'
