---
- name: Role Post-Install
  when:
    - ansible_host in k3s_map.server.hosts
    - certmanager_map.metrics.service.monitor.enabled
  run_once: true
  block:
    - name: Update chart postinstall fact
      ansible.builtin.set_fact:
        certmanager_postinstall: true

    - name: Update chart postinstall values
      kubernetes.core.helm:
        chart_ref: '{{ certmanager_map.helm.chart.reference }}'
        chart_version: '{{ certmanager_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
        name: '{{ certmanager_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ certmanager_vars.kubernetes.namespace }}'
        timeout: '{{ certmanager_map.helm.timeout }}'
        values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
        reset_values: false
        reuse_values: true
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
