---
- name: Import facts
  ansible.builtin.include_role:
    name: k3s
    tasks_from: facts

- name: Role Post-Install
  when: ansible_host in k3s_map.server.hosts
  run_once: true
  block:
    - name: Set chart postinstall fact
      ansible.builtin.set_fact:
        victorialogs_postinstall: true

    - name: Update chart postinstall values
      kubernetes.core.helm:
        chart_ref: '{{ victorialogs_map.helm.chart.reference }}'
        chart_version: '{{ victorialogs_vars.kubernetes.helm.chart.version }}'
        kubeconfig: '{{ k3s_map.cluster.kubeconfig }}'
        name: '{{ victorialogs_vars.kubernetes.helm.chart.alias }}'
        namespace: '{{ victorialogs_vars.kubernetes.namespace }}'
        values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
        reset_values: false
        reuse_values: true
        wait: true
      register: result
      delay: 1
      retries: 3
      until: result is not failed
